url: http://ggentili.github.io
baseurl: 

# Site settings
title: Unità Pastorale 22 Ponte Valleceppi
email: your-email@domain.com
description: "Unità Pastorale 22 - Ponte Valleceppi, Pretola, Sant'Egidio-Lidarno, Ripa-Civitella d'Arna-Pilonico Paterno, Pianello - UP della Archidiocesi Perugia-Città della Pieve"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Santa Maria Maddalena
  pic: 1
  position: in Ponte Valleceppi
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: San Nicolò
  pic: 2
  position: in Pretola
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Sant'Egidio
  pic: 3
  position: in Sant'Egidio
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/ggentili
  - title: facebook
    url: https://www.facebook.com/pontevalleceppiup
    
# Postal address (add as many lines as necessary)
address:
  - line: Ponte Valleceppi - Via Bologna, 35 - Perugia - 0756920188
  - line: Pretola - Via Romagna, 19 - Perugia - 0756920857
  - line: Sant'Egidio - Via Ortolana, 9 - Perugia - 0756920273

# Build settings
markdown: kramdown
permalink: pretty
